package application;

import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.ResourceBundle;

import dao.UsersDAO;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.layout.AnchorPane;
import utils.TransactionUtils;
import utils.UserUtils;
import validations.UserValidations;

public class ForgotPasswordSceneController extends Controller implements Initializable {
	@FXML
	private AnchorPane scenePaneForgotPassword;
	@FXML
	private Label lblNote;
	@FXML
	private TextField txtEmail;
	@FXML
	private Button btnVerifyEmail;
	@FXML
	private AnchorPane anchorPaneResetPassword;
	@FXML
	private Button btnChangeEmail;
	@FXML
	private Label lblBankName;
	
	List<String> temporaryVeriedEmailsList;

	// Event Listener on Button[#btnVerifyEmail].onAction
	@FXML
	public void handleVerifyEmailAction(ActionEvent event) throws Exception {
		// TODO Autogenerated
		String title = null;
		String headerText = null;
		String contentText = null;
		
		String email = txtEmail.getText();
		
		if(temporaryVeriedEmailsList.contains(email)) {
			btnVerifyEmail.setText("Email Verified");
			btnVerifyEmail.setStyle("-fx-background-color: green;-fx-text-fill: black;");
			btnVerifyEmail.setDisable(true);
			txtEmail.setDisable(true);
			btnChangeEmail.setVisible(true);
			headerText = "Email Already Verified";
			AnchorPane transferOther = (AnchorPane)FXMLLoader.load(getClass()
					.getResource(SceneFiles.RESET_PASSWORD_ANCHOR_PANE));
			anchorPaneResetPassword.getChildren().setAll(transferOther.getChildren());
			FXMLLoader loader = new FXMLLoader(getClass().getResource(SceneFiles.RESET_PASSWORD_ANCHOR_PANE));
			Parent root = loader.load();
			ResetPasswordAnchorPaneController resetPasswordController = loader.getController();
			resetPasswordController.setResetPasswordEmail(email);
			AlertController.showSuccess(title, headerText, contentText);
			return;
		}
		
		boolean isEmailValid = UserValidations.isEmailValid(email);
		boolean emailExists = UsersDAO.userExistsByEmail(email);

		title = "Forgot Password Email Verification";
		if (!isEmailValid) {
			headerText = "Invalid Email";
			AlertController.showError(title, headerText, contentText);
			return;
		}
		
		if (!emailExists) {
			headerText = "User with the given email does not exist";
			AlertController.showError(title, headerText, contentText);
			return;
		} 

		int generatedOTP = TransactionUtils.generateOTP();
		Date generatedOTPTimestamp = new Date();
		boolean sentOTP = UserUtils.sendEmailVerificationOTP(email, generatedOTP);
		if(sentOTP) {
			boolean isEmailVerified = DialogController.verifyEmailDialog(email, generatedOTP, generatedOTPTimestamp);
			if (isEmailVerified) {
				temporaryVeriedEmailsList.add(email);
				btnVerifyEmail.setText("Email Verified");
				btnVerifyEmail.setStyle("-fx-background-color: green;-fx-text-fill: black;");
				btnVerifyEmail.setDisable(true);
				txtEmail.setDisable(true);
				btnChangeEmail.setVisible(true);
				AnchorPane transferOther = (AnchorPane)FXMLLoader.load(getClass()
						.getResource(SceneFiles.RESET_PASSWORD_ANCHOR_PANE));
				anchorPaneResetPassword.getChildren().setAll(transferOther.getChildren());
				FXMLLoader loader = new FXMLLoader(getClass().getResource(SceneFiles.RESET_PASSWORD_ANCHOR_PANE));
				Parent root = loader.load();
				ResetPasswordAnchorPaneController resetPasswordController = loader.getController();
				resetPasswordController.setResetPasswordEmail(email);
			}
			else {
				headerText = "Email Verification Failed";
				AlertController.showError(title, headerText, contentText);
				return;
			}
		}
		else {
			headerText = "Failed to send verification code";
			AlertController.showError(title, headerText, contentText);
			return;
		}
	}
	// Event Listener on Button[#btnChnageEmail].onAction
	@FXML
	public void handleChangeEmailAction(ActionEvent event) {
		// TODO Autogenerated
		btnVerifyEmail.setText("Verify Email");
		btnVerifyEmail.setStyle("");
		btnVerifyEmail.setDisable(false);
		txtEmail.setDisable(false);
		btnChangeEmail.setVisible(false);
		anchorPaneResetPassword.getChildren()
		.removeAll(anchorPaneResetPassword.getChildren());
	}
	@Override
	public void initialize(URL url, ResourceBundle resourceBundle) {
		// TODO Auto-generated method stub
		btnChangeEmail.setVisible(false);
		temporaryVeriedEmailsList = new ArrayList<>();
	}

	// Event Listener on Hyperlink[#hyperlinkToLogin].onAction
	@FXML
	public void handleSwitchToLoginScene(ActionEvent event) throws IOException {
		// TODO Autogenerated
		SwitchSceneController.invokeLayout(event, SceneFiles.LOGIN_SCENE_LAYOUT);
	}
}
