package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.scene.control.RadioButton;

import javafx.scene.layout.AnchorPane;
import javafx.scene.control.ToggleGroup;

public class TransactionsSceneController extends Controller implements Initializable {
	@FXML
	private AnchorPane anchorPaneTransactionScene;
	@FXML
	private AnchorPane anchorPane;
	@FXML
	private static AnchorPane cardsPane;
	@FXML
	private static AnchorPane accountsPane;
	@FXML
	private Label lblHome;
	@FXML
	private Label lblDisplayingAccountTransactions;
	@FXML
	private Button btnLogout;
	@FXML
	private Label lblCurrentUserEmail;
	@FXML
	private Button btnGoBack;
	@FXML
	private RadioButton radioBtnCredit;
	@FXML
	private RadioButton radioBtnSavings;
	@FXML
	private ToggleGroup TransactionType;
	
		@FXML
		public void handleLogoutAction(ActionEvent event) throws IOException {
			// TODO Autogenerated
			isSessionActive = false;
			user = null;
			SwitchSceneController.invokeLayout(event, SceneFiles.LOGIN_SCENE_LAYOUT);
		}
		@FXML
		public void invokeHomeSceneLayout(ActionEvent event) throws IOException {
			// TODO Autogenerated
			SwitchSceneController.invokeLayout(event, SceneFiles.HOME_SCENE_LAYOUT);
		}
		@Override
		public void initialize(URL url, ResourceBundle arg1) {
			// TODO Auto-generated method stub
			refreshState();
			
			try {
				
				AnchorPane accounts = (AnchorPane)FXMLLoader
						.load(getClass()
								.getResource(SceneFiles.ACCOUNT_TRANSACTIONS));
				AnchorPane cards = (AnchorPane)FXMLLoader
						.load(getClass()
								.getResource(SceneFiles.CARD_TRANSACTIONS));
					
				if(user.getCreditCard().getCreditCardId() == null) {
					radioBtnCredit.setVisible(false);
					radioBtnSavings.setVisible(false);
					anchorPane.getChildren().setAll(accounts.getChildren());
					lblDisplayingAccountTransactions.setText("Displaying Account Transactions");
				}
				else {
					anchorPane.getChildren().setAll(cards.getChildren());
//					lblDisplayingAccountTransactions.setVisible(false);
					lblDisplayingAccountTransactions.setText("Displaying Card Transactions");
				}
				
			} catch (IOException e) {
				// TODO: handle exception
			}
		}
		
		@FXML
		public void displayTransactions(ActionEvent event) throws IOException {
			
			AnchorPane cards = (AnchorPane)FXMLLoader.load(getClass().getResource(SceneFiles.CARD_TRANSACTIONS));
			AnchorPane accounts = (AnchorPane)FXMLLoader.load(getClass().getResource(SceneFiles.ACCOUNT_TRANSACTIONS));
			if(user.getCreditCard().getCreditCardId() == null) {
				radioBtnCredit.setVisible(false);
				radioBtnSavings.setVisible(false);
				anchorPane.getChildren().setAll(accounts.getChildren());
			}
			else {
				if(radioBtnCredit.isSelected()) {
					anchorPane.getChildren().setAll(cards.getChildren());
					lblDisplayingAccountTransactions.setVisible(true);
					lblDisplayingAccountTransactions.setText("Displaying Card Transactions");
				}
				else {
					anchorPane.getChildren().setAll(accounts.getChildren());
					lblDisplayingAccountTransactions.setVisible(true);
					lblDisplayingAccountTransactions.setText("Displaying Account Transactions");
				}
			}
		}
}
